#
# Configure NGINX http
#
nginx_config_http_template_enable: true
nginx_config_http_template:
  # Proxy
  - template_file: http/default.conf.j2
    deployment_location: /etc/nginx/conf.d/proxy.conf
    config:
      core:
      custom_directives:
        - proxy_buffering off;
        - proxy_set_header   X-Real-IP $remote_addr;
        - proxy_set_header   X-Scheme $scheme;
        - proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        - proxy_set_header   Host $http_host;
        - proxy_connect_timeout 300s;
        - proxy_send_timeout 600;
        - proxy_read_timeout 600;
        - proxy_buffer_size 64k;
        - proxy_buffers 16 32k;
        - proxy_busy_buffers_size 64k;
        - proxy_temp_file_write_size 64k;
        - proxy_pass_header Set-Cookie;
        - proxy_redirect off;
        - proxy_hide_header Vary;
        - proxy_set_header Accept-Encoding '';
        - proxy_ignore_headers Cache-Control Expires;
  # CUSTOM
  - template_file: http/default.conf.j2
    deployment_location: /etc/nginx/conf.d/custom.conf
    config:
      custom_directives:
        - server {
        - listen 0.0.0.0:8281 default_server;
        - server_name localhost; }
  - template_file: http/default.conf.j2
    deployment_location: /etc/nginx/conf.d/default.conf
    config:
      servers:
        - core:
            listen:
              - port: 8081
                server_name: localhost
                default_server: true
          locations:
            - location: /
              core:
                root: /usr/share/nginx/html
                index: index.php index.html index.htm
                try_files:
                  files: $uri
                  uri: /uri /index.php$is_args$args
                  code: uri
            - location: /\.ht
              access:
                allow: 127.0.0.1
                deny: 192.168.1.100
        - core:
            server_name: localhost
            client_max_body_size: 512k
            listen:
              - address: 0.0.0.0
                port: 80
                default_server: true
              - address: 0.0.0.0
                port: 443
                ssl: false
                default_server: true
              - address: "[::]"
                port: 80
                default_server: true
  # Client
  - template_file: http/default.conf.j2
    deployment_location: /etc/nginx/conf.d/client.conf
    config:
      core:
        client_body_buffer_size: 8k
        client_body_in_file_only: false  # Boolean -- Can also be set to 'clean'
        client_body_in_single_buffer: false  # Boolean
        client_body_timeout: 300s
        client_header_buffer_size: 4k  # Not available in the 'location' context
        client_header_timeout: 300s  # Not available in the 'location' context
        client_max_body_size: 512m
        connection_pool_size: 256  # Not available in the 'location' context
        keepalive_disable: msie6  # String or a list of strings
        keepalive_requests: 1000  # Number
        keepalive_time: 1h
        keepalive_timeout:  # 75s  # Can alternatively be set to a 'timeout' string
          timeout: 75s  # Required
          header_timeout: 75s
        large_client_header_buffers:  # Not available in the 'location' context
          number: 8  # Required number
          size: 16k  # Required
      custom_directives:
        - request_pool_size 4k;
  # Cache
  - template_file: http/default.conf.j2
    deployment_location: /etc/nginx/conf.d/cache.conf
    config:
      core:
      custom_directives:
        - fastcgi_cache_path /tmp/nginx_fastcgi_cache levels=1:2 keys_zone=phpcache:100m max_size=1g inactive=60m use_temp_path=off;
        - fastcgi_cache_key "$scheme$request_method$host$request_uri";
  # GZIP
  - template_file: http/default.conf.j2
    deployment_location: /etc/nginx/conf.d/gzip.conf
    config:
      gunzip:  # Configure GUNZIP
        enable: true  # Boolean
        buffers:
          number: 32  # Required
          size: 4k  # Required
      gzip:  # Configure GZIP
        enable: true  # Boolean
        buffers:
          number: 32  # Required
          size: 4k  # Required
        comp_level: 1
        #disable: []  # String or a list of strings
        http_version: 1.1  # Can be set to '1.0' or '1.1'
        min_length: 20
        # proxied: []  # String or a list of strings -- Can alternatively be set to 'false'
        # types: []  # String or a list of strings
        vary: false  # Boolean
