all:
  children:
    asifa_hollywood_org_group:
      hosts:
        asifa_hollywood_org:
    production:
      hosts:
        asifa_hollywood_org:
          ansible_host: 3.90.46.111
          ansible_port: 22
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
          #
          www_user: "asifa_hollywood_org"
